[build]
  base = "" 
  publish = "backend/public"
  command = "npm install && npm install --prefix backend"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[context.production.environment]
  REACT_APP_API_BASE_URL = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
